### ISSUE TITLE
计算方法过于复杂，容易导致绘制的时候创建过多的layout对象

### ISSUE THREAD

**Issue by 7heaven** [hongyangAndroid/MixtureTextView#4]
可以考虑使用DynamicLayout + 动态添加Span的方式来做，在需要给子控件让出空间的位置使用宽度可定但是不可见的Span来给Layout创建文字内部的间隔，这个整个布局内容复杂也不会导致计算和绘制时间的大幅度增加。甚至可以实现拖动子控件的动态排版。

**Comment by lovewysy** [comment]
08-08 13:35:59.970: E/CrashHandler(3539): java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
08-08 13:35:59.970: E/CrashHandler(3539):   at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
08-08 13:35:59.970: E/CrashHandler(3539):   at java.util.ArrayList.get(ArrayList.java:304)
08-08 13:35:59.970: E/CrashHandler(3539):   at com.bsjvideo.notice.MixtureTextView.tryDraw(MixtureTextView.java:183)
08-08 13:35:59.970: E/CrashHandler(3539):   at com.bsjvideo.notice.MixtureTextView.dispatchDraw(MixtureTextView.java:281)
两个错误 ，我在看我能不能改改再用。
